
build:
  version: "1.0"

customer:
  message: "Welcome to customer service related local Productions APIs"
  contactDetails:
    name: "Manoj - Technical PROD Lead"
    email: "manoj@practice.com"
  onCallSupport:
    - +919884137236