spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri:
      #native:
          #search-locations: "classpath:/config"

server:
  port: 8071